### ISSUE TITLE
Ope

### ISSUE THREAD

**Issue by Volodya-music** [BreezeWhite/oemer#30]
**Describe the bug**

**Input Image**
The original image that triggers this bug (not the image name). In *.jpg* or *.png* format, *.pdf* file will not work.

You can attach the image file by simply dragging the file to the text area.

***IMPORTANT*** The issue will be closed directly if you don't provide the image and the issue relates to transcription bugs.

**Full Traceback**
The complete error traceback.

**Command You Execute**
The complete command you executed. Should looks like `oemer sheet.png --without-deskew`, including flags you added.

**Comment by Volodya-music** [comment]
volodyagolotovskij@MacBook-Pro oemer % pip install .

Processing /Users/volodyagolotovskij/oemer
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of oemer to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from oemer) (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu
volodyagolotovskij@MacBook-Pro oemer % pip install onnxruntime

Requirement already satisfied: onnxruntime in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.15.1)
Requirement already satisfied: coloredlogs in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from onnxruntime) (15.0.1)
Requirement already satisfied: flatbuffers in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from onnxruntime) (23.5.26)
Requirement already satisfied: numpy>=1.21.6 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from onnxruntime) (1.24.4)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from onnxruntime) (23.1)
Requirement already satisfied: protobuf in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from onnxruntime) (4.23.4)
Requirement already satisfied: sympy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from onnxruntime) (1.12)
Requirement already satisfied: humanfriendly>=9.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from coloredlogs->onnxruntime) (10.0)
Requirement already satisfied: mpmath>=0.19 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from sympy->onnxruntime) (1.3.0)
volodyagolotovskij@MacBook-Pro oemer %

**Comment by BreezeWhite** [comment]
Please follow the issue template. Closing
