### ISSUE TITLE
TypeError: cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by pingpeng1017** [BreezeWhite/oemer#32]
Hi, I keep getting this error when I try to run the train.py file.

File "C:\Users\Minjoo Lee\.conda\envs\oemer\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

TypeError: cannot pickle 'weakref' object

         [[{{node PyFunc}}]]
         [[IteratorGetNext]] [Op:__inference_train_function_35917]

**Comment by BreezeWhite** [comment]
The `oemer/lib/multiprocessing/reduction.py` isn't part of `oemer`, therefore I could not help on the problem. Also please follow the issue template format. Closing this due to lack of information.
