### ISSUE TITLE
rythm fails in simple melodies

### ISSUE THREAD

**Issue by zoldaten** [BreezeWhite/oemer#36]
thanks for a wonderful project!
works like a charm.

but sometimes i see rythm failing in very simple melodies:

![3](https://github.com/BreezeWhite/oemer/assets/29411817/e4205808-77c6-4e05-8eb0-cb0a5759018c)
![3_teaser](https://github.com/BreezeWhite/oemer/assets/29411817/5e705b84-66bf-47b6-8a06-fcb8f3283475)
mp3:
[3.zip](https://github.com/BreezeWhite/oemer/files/12659844/3.zip)

**Comment by BreezeWhite** [comment]
It's probably due to the input size of your image. `oemer` expects an A4-like image, which your image has the opposite ratio of width and height.
