### ISSUE TITLE
error always occurs when extracting stafflines

### ISSUE THREAD

**Issue by songkq** [BreezeWhite/oemer#4]
2022-04-18 13:06:51 Dewarping
2022-04-18 13:07:00 Extracting stafflines
/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
91 321 3
322 552 3
553 783 3
784 1014 3
1015 1245 1246 1476 1
1477 1707 1708 1940 Traceback (most recent call last):
  File "/usr/local/bin/oemer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/oemer/ete.py", line 261, in main
    mxl_path = extract(args)
  File "/usr/local/lib/python3.7/dist-packages/oemer/ete.py", line 157, in extract
    staffs, zones = staff_extract()
  File "/usr/local/lib/python3.7/dist-packages/oemer/staffline_extraction.py", line 366, in extract
    f"Unit sizes not consistent (th: {unit_size_diff_th}): {norm(unit_size)}")
oemer.exceptions.StafflineUnitSizeInconsistent: Unit sizes not consistent (th: 0.1): [0.05035999 0.0562467  0.05098227 0.01743093 0.17501989]

**Comment by songkq** [comment]
![image](https://user-images.githubusercontent.com/30183023/163813168-17e85797-a9a5-4312-ab31-330eeb5e4c0c.png)

**Comment by songkq** [comment]
@BreezeWhite hi，could you please to give some kind advices for the above mentioned issues?

**Comment by songkq** [comment]
Here are some of my testcases
![cell_06](https://user-images.githubusercontent.com/30183023/163813352-d4b7fc4b-be1b-4284-9ba3-364d0aaf9dea.jpg)
![cell_03d](https://user-images.githubusercontent.com/30183023/163813364-12aec450-a650-4c5a-8f03-6b23ee1358a7.jpg)
![cell_05](https://user-images.githubusercontent.com/30183023/163813370-fada4423-fa1f-4422-9b21-481e98aecd9e.jpg)

**Comment by BreezeWhite** [comment]
I've tried all your images, and the errors seem to relate to the qualities of your images. I suggest you re-photo your images in a better condition, with brighter environment, more clear quality, and no blurry to the symbols. Also please center your photo angle right above your score, making everything is both vertically and horizontally aligned, since the images you provided look pretty skewed.

**Comment by songkq** [comment]
> I've tried all your images, and the errors seem to relate to the qualities of your images. I suggest you re-photo your images in a better condition, with brighter environment, more clear quality, and no blurry to the symbols. Also please center your photo angle right above your score, making everything is both vertically and horizontally aligned, since the images you provided look pretty skewed.

Thanks for your reply. I wonder if we can adjust some of the hyperparameters during the dewarping step to fit skewed or curve stafflines.

**Comment by BreezeWhite** [comment]
Sorry but I'm afraid I could not help too much since I'm too busy recently. But of course you could try to tune the parameters by yourself and see if the results become better.
