### ISSUE TITLE
Oemer is not Recognized as a cmdlet

### ISSUE THREAD

**Issue by bmontney** [BreezeWhite/oemer#41]
**Describe the bug**

I am decently new to coding and have installed oemer but when I try to run oemer it says that oemer is not a recognized cmdlet. I have been stuck on this problem for a while and have tried to add it to my environment path and it wouldn't work. Therefore, I was just wondering if you had any ideas. Thank you very much for your help

**Input Image**
The original image that triggers this bug (not the image name). In *.jpg* or *.png* format, *.pdf* file will not work.

![mary](https://github.com/BreezeWhite/oemer/assets/90990314/a3832a52-cb06-426a-b4b5-741de5fc09f1)

***IMPORTANT*** The issue will be closed directly if you don't provide the image and the issue relates to transcription bugs.

**Full Traceback**
Error:     Oemer : The term 'Oemer' is not recognized as the name of a cmdlet, function, script 
              file, or operable program. Check the spelling of the name, or if a path was included,   
              verify that the path is correct and try again.
              At line:1 char:1
              + Oemer 'mary.jpg'
              + ~~~~~
              + CategoryInfo          : ObjectNotFound: (Oemer:String) [], CommandNotFoundExcept  
              ion
             + FullyQualifiedErrorId : CommandNotFoundException

**Command You Execute**
The complete command you executed. Should looks like `oemer sheet.png --without-deskew`, including flags you added.

Code :   Oemer 'mary.jpg'

**Comment by BreezeWhite** [comment]
It's 'oemer', not 'Oemer'. The first 'o' is lower case.
