### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Arduinoz-R-Awsome** [BreezeWhite/oemer#47]
The `Assertion Error` only occurs during the *Dewarping* phase. 

The image is slightly blurry. Maybe this is the problem?
![Ligeti](https://github.com/BreezeWhite/oemer/assets/98224562/469eb858-4be1-49cb-87df-ad3abfe5ac13)

The full error and the message that preceded the error:

**2023-11-08 11:44:12 Dewarping
Traceback (most recent call last):
  File "/Users/Micah/anaconda3/bin/oemer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/Micah/anaconda3/lib/python3.11/site-packages/oemer/ete.py", line 276, in main
    mxl_path = extract(args)
               ^^^^^^^^^^^^^
  File "/Users/Micah/anaconda3/lib/python3.11/site-packages/oemer/ete.py", line 146, in extract
    coords_x, coords_y = estimate_coords(staff)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Micah/anaconda3/lib/python3.11/site-packages/oemer/dewarp.py", line 271, in estimate_coords
    new_gg_map = connect_nearby_grid_group(gg_map, grid_groups, grid_map, grids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Micah/anaconda3/lib/python3.11/site-packages/oemer/dewarp.py", line 186, in connect_nearby_grid_group
    assert grid_id in grid_groups[label].gids, f"{grid_id}, {label}"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: -1, -1**

I don't know if this means anything, but it always returns this message when oemer an image:
**/Users/Micah/anaconda3/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CoreMLExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
/Users/Micah/anaconda3/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(**

The command I executed: `oemer Ligeti.jpeg ` (I was in the same directory as the image)

System information:
**macOS Monterey
Version 12.7

MacBook Pro (Retina, 13-inch, Early 2015)
Processor: 2.7 GHz Dual-Core Intel Core i5
Memory: 8 GB 1867 MHz DDR3
Startup Disk: MacOS
Graphics: Intel Iris Graphics 6100 1536 MB**
My interpreter that I ran the command in was [fish](https://fishshell.com/)

For extra information, I successfully ran oemer on the image below.
<img width="557" alt="sheet_music" src="https://github.com/BreezeWhite/oemer/assets/98224562/cb8a50ae-97a9-4676-b34e-15b81bf8d82b">

**Comment by BreezeWhite** [comment]
You can add `--without-deskew` to skip the dewarping step.
